# Generated by Django 5.2 on 2025-04-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_tarea_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='contenido',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='fecha_creación',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='titulo',
        ),
        migrations.AddField(
            model_name='tarea',
            name='Contraseña',
            field=models.CharField(default='asd', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarea',
            name='Correo',
            field=models.EmailField(default='asd@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarea',
            name='Nombre',
            field=models.CharField(default='asd', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarea',
            name='Username',
            field=models.CharField(default='asd', max_length=150),
            preserve_default=False,
        ),
    ]
