# Generated by Django 5.2 on 2025-04-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('todoapp', '0003_remove_tarea_categoria_remove_tarea_contenido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
