# Generated by Django 5.2 on 2025-05-24 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('todoapp', '0003_remove_tarea_categoria_remove_tarea_contenido_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
