# Generated by Django 5.2 on 2025-04-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_libro_test_delete_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('Libro', 'Libro'), ('Manga', 'Manga'), ('Anime', 'Anime'), ('Película', 'Película'), ('Cómic', 'Cómic')], max_length=20)),
                ('autor', models.CharField(blank=True, max_length=100, null=True)),
                ('estudio', models.CharField(blank=True, max_length=100, null=True)),
                ('director', models.CharField(blank=True, max_length=100, null=True)),
                ('editorial', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_lanzamiento', models.DateField(blank=True, null=True)),
                ('imagen', models.URLField(blank=True)),
            ],
        ),
    ]
